services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/my-books-frontend
      - node_modules:/my-books-frontend/node_modules
    tty: true
    ports:
      - 5173:5173
      - 4173:4173

volumes:
  node_modules:
